import { ModuleShell } from "@/components/module-shell";

const documents = {
  termos: { title: "Termos de Uso", description: "Regras para usar o Nexus Brasil de forma segura e responsável.", sections: [["1. Aceitação", "Ao criar uma conta ou utilizar a plataforma, você concorda com estes termos. Contas de menores devem observar a legislação aplicável e a autorização de responsável quando necessária."], ["2. Uso permitido", "Não publique conteúdo ilegal, fraudulento, abusivo ou que viole direitos de terceiros. Tentativas de manipulação, spam ou acesso não autorizado podem resultar em suspensão."], ["3. Conteúdo e marketplace", "Você mantém os direitos sobre o conteúdo que publica e declara possuir autorização para utilizá-lo. Vendedores são responsáveis pela veracidade das ofertas, entrega e obrigações legais."], ["4. Pagamentos", "Pagamentos reais somente serão processados após a integração com provedor autorizado. O Nexus não armazena dados de cartão."], ["5. Limitação", "O modo demonstração não cria obrigações comerciais, financeiras ou de disponibilidade. Estes termos devem passar por revisão jurídica antes do lançamento comercial."]] },
  privacidade: { title: "Política de Privacidade", description: "Como os dados serão tratados quando as integrações reais forem ativadas.", sections: [["1. Dados coletados", "Poderemos tratar dados de conta, perfil, uso, publicações, pedidos e preferências necessários para prestar o serviço."], ["2. Finalidades", "Os dados serão usados para autenticação, personalização, segurança, atendimento, execução de pedidos e melhoria do produto."], ["3. Compartilhamento", "Dados serão compartilhados apenas com provedores essenciais, autoridades quando exigido por lei ou mediante consentimento válido."], ["4. Seus direitos", "Nos termos da LGPD, você poderá solicitar acesso, correção, portabilidade, exclusão e informações sobre o tratamento."], ["5. Segurança", "Segredos ficam no servidor, o banco utiliza políticas por usuário e ações sensíveis são registradas. Nenhum sistema é absolutamente invulnerável."]] },
  cookies: { title: "Política de Cookies", description: "Controle claro sobre preferências e medição.", sections: [["Essenciais", "Necessários para sessão, segurança, idioma e funcionamento básico."], ["Preferências", "Armazenam opções como tema claro ou escuro no dispositivo."], ["Analytics", "Somente serão ativados após configuração e consentimento aplicável."], ["Controle", "O painel de consentimento permitirá aceitar, recusar ou alterar categorias não essenciais."]] },
  diretrizes: { title: "Diretrizes da Comunidade", description: "Um espaço forte depende de colaboração com respeito.", sections: [["Seja útil", "Compartilhe conhecimento verdadeiro, contexto e feedback construtivo."], ["Respeite pessoas", "Assédio, discurso de ódio, ameaças e exposição de dados pessoais não são permitidos."], ["Proteja a autoria", "Publique apenas conteúdo próprio, licenciado ou autorizado e indique fontes."], ["Negocie com honestidade", "Ofertas enganosas, manipulação de avaliações e promessas de renda garantida serão removidas."], ["Denuncie problemas", "Use as ferramentas de denúncia. A moderação deve avaliar contexto, reincidência e gravidade."]] },
} as const;

export function LegalDocument({ type }: { type: keyof typeof documents }) {
  const document = documents[type];
  return <ModuleShell active="" eyebrow="CENTRAL DE CONFIANÇA" title={document.title} description={document.description}><article className="legal-document"><div className="legal-notice">Documento demonstrativo — exige revisão jurídica antes do lançamento comercial.</div>{document.sections.map(([title, content]) => <section key={title}><h2>{title}</h2><p>{content}</p></section>)}{(type === "termos" || type === "privacidade") && <section><h2>Revisão interna de sites</h2><p>No Builder, você pode autorizar separadamente o armazenamento do código gerado e de uma versão revisada para análise privada pelo proprietário do Nexus. A opção vem desmarcada, exige login e não transfere a titularidade nem autoriza publicação ou revenda. A revisão usa regras locais, sem enviar essa cópia a outro provedor de IA. Você pode consultar e remover suas cópias em Builder → Cópias internas autorizadas. Sites gerados pela própria conta proprietária entram no laboratório privado automaticamente.</p></section>}<small>Última atualização: 13 de setembro de 2026.</small></article></ModuleShell>;
}
